security:
    # Configuración de hashers de contraseñas
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Proveedores de usuarios
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email

    # Configuración de firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: auth_login
                check_path: auth_login
                enable_csrf: true
                username_parameter: email
                password_parameter: password
            logout:
                path: auth_logout
                target: auth_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 días
                path: /

    # Control de acceso
    access_control:
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/auth/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        - { path: ^/denuncia/listar, roles: ROLE_USER }
        - { path: ^/denuncia/listar-todas, roles: ROLE_ADMIN }
        - { path: ^/notificacion, roles: ROLE_USER }
        - { path: ^/evidencia, roles: ROLE_USER }
        - { path: ^/moderador, roles: ROLE_MODERATOR }
        - { path: ^/supervisor, roles: ROLE_SUPERVISOR }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/usuario_registro, roles: PUBLIC_ACCESS }
        - { path: ^/usuario_login, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
